// src/data/questions.js

/**
 * Все вопросы для мини-игр в одном месте.
 * Структура:
 * {
 *   [categoryKey]: [
 *     {
 *       id: string,
 *       question: string,
 *       options: string[],
 *       correctIndex: number
 *     },
 *     ...
 *   ]
 * }
 */
const QUESTIONS = {
    wordFlex: [
        {
          id: 'wf-1',
          question: 'Which word is a synonym of swift?',
          options: ['Bright', 'Quick', 'Strong', 'Deep'],
          correctIndex: 1,
        },
        {
          id: 'wf-2',
          question: 'Which word is the opposite of ancient?',
          options: ['Old', 'Future', 'Modern', 'Mythical'],
          correctIndex: 2,
        },
        {
          id: 'wf-3',
          question: 'Complete the analogy: Fire is to hot as ice is to...',
          options: ['Wet', 'Cold', 'Blue', 'Solid'],
          correctIndex: 1,
        },
        {
          id: 'wf-4',
          question: 'Which word is most similar to silent?',
          options: ['Quiet', 'Sound', 'Sleep', 'Speak'],
          correctIndex: 0,
        },
        {
          id: 'wf-5',
          question: 'Which word doesn’t belong? Book, Chapter, Page, Window',
          options: ['Book', 'Chapter', 'Page', 'Window'],
          correctIndex: 3,
        },
        {
          id: 'wf-6',
          question: 'What is the antonym of accept?',
          options: ['Invite', 'Deny', 'Refuse', 'React'],
          correctIndex: 2,
        },
        {
          id: 'wf-7',
          question: 'Which word is closest in meaning to fragile?',
          options: ['Soft', 'Gentle', 'Weak', 'Breakable'],
          correctIndex: 3,
        },
        {
          id: 'wf-8',
          question: 'Which word is most unlike the others? Run, Jog, Sprint, Sit',
          options: ['Run', 'Jog', 'Sprint', 'Sit'],
          correctIndex: 3,
        },
        {
          id: 'wf-9',
          question: 'What is the opposite of increase?',
          options: ['Expand', 'Multiply', 'Decrease', 'Raise'],
          correctIndex: 2,
        },
        {
          id: 'wf-10',
          question: 'Choose the synonym of bright.',
          options: ['Clever', 'Dim', 'Heavy', 'Cold'],
          correctIndex: 0,
        },
        {
          id: 'wf-11',
          question: 'Which word is the odd one out? Apple, Banana, Chair, Orange',
          options: ['Apple', 'Banana', 'Chair', 'Orange'],
          correctIndex: 2,
        },
        {
          id: 'wf-12',
          question: 'Which word means the same as brave?',
          options: ['Strong', 'Fearless', 'Proud', 'Angry'],
          correctIndex: 1,
        },
        {
          id: 'wf-13',
          question: 'What’s the antonym of difficult?',
          options: ['Easy', 'Simple', 'Clear', 'Short'],
          correctIndex: 0,
        },
        {
          id: 'wf-14',
          question: 'Complete the analogy: Teacher is to school as doctor is to...',
          options: ['Clinic', 'Medicine', 'Nurse', 'Health'],
          correctIndex: 0,
        },
        {
          id: 'wf-15',
          question: 'Which word is similar to gigantic?',
          options: ['Huge', 'Tiny', 'Loud', 'Slow'],
          correctIndex: 0,
        },
        {
          id: 'wf-16',
          question: 'Which word is opposite in meaning to full?',
          options: ['Heavy', 'Small', 'Empty', 'Hollow'],
          correctIndex: 2,
        },
        {
          id: 'wf-17',
          question: 'Choose the synonym of happy.',
          options: ['Tired', 'Joyful', 'Noisy', 'Silent'],
          correctIndex: 1,
        },
        {
          id: 'wf-18',
          question: 'Which word does not belong? Clock, Watch, Timer, Spoon',
          options: ['Clock', 'Watch', 'Timer', 'Spoon'],
          correctIndex: 3,
        },
        {
          id: 'wf-19',
          question: 'Which word is closest in meaning to honest?',
          options: ['True', 'Friendly', 'Simple', 'Loud'],
          correctIndex: 0,
        },
        {
          id: 'wf-20',
          question: 'What is the opposite of safe?',
          options: ['Secure', 'Cautious', 'Dangerous', 'Reliable'],
          correctIndex: 2,
        },
        {
          id: 'wf-21',
          question: 'Complete the analogy: Bird is to fly as fish is to...',
          options: ['Swim', 'Water', 'Gills', 'Dive'],
          correctIndex: 0,
        },
        {
          id: 'wf-22',
          question: 'Which word is a synonym of strange?',
          options: ['Boring', 'Unusual', 'Clear', 'Weak'],
          correctIndex: 1,
        },
        {
          id: 'wf-23',
          question: 'What’s the antonym of sharp?',
          options: ['Quick', 'Dull', 'Clear', 'Bright'],
          correctIndex: 1,
        },
        {
          id: 'wf-24',
          question: 'Which word doesn’t belong? Chair, Table, Couch, Pencil',
          options: ['Chair', 'Table', 'Couch', 'Pencil'],
          correctIndex: 3,
        },
        {
          id: 'wf-25',
          question: 'What word is most opposite to freedom?',
          options: ['Order', 'Rule', 'Captivity', 'Law'],
          correctIndex: 2,
        },
        {
          id: 'wf-26',
          question: 'Which is a synonym of laugh?',
          options: ['Smile', 'Giggle', 'Sneeze', 'Scream'],
          correctIndex: 1,
        },
        {
          id: 'wf-27',
          question: 'Choose the opposite of light (weight).',
          options: ['Strong', 'Heavy', 'Bright', 'Airy'],
          correctIndex: 1,
        },
        {
          id: 'wf-28',
          question: 'Which word best completes the analogy: Rain is to wet as snow is to...',
          options: ['Warm', 'Cold', 'Ice', 'Water'],
          correctIndex: 1,
        },
        {
          id: 'wf-29',
          question: 'Which word is the odd one out? Sing, Dance, Cook, Silence',
          options: ['Sing', 'Dance', 'Cook', 'Silence'],
          correctIndex: 3,
        },
        {
          id: 'wf-30',
          question: 'Which word is most similar to fast?',
          options: ['Quick', 'Loud', 'Slow', 'Long'],
          correctIndex: 0,
        },
      ],
    
      // ─────────── Verbal Thinking – Verbal Logic ───────────
      verbalLogic: [
        {
          id: 'vl-1',
          question: 'Which word doesn’t belong? Dog, Cat, Lion, Car',
          options: ['Dog', 'Cat', 'Lion', 'Car'],
          correctIndex: 3,
        },
        {
          id: 'vl-2',
          question: 'Which sentence is logically incorrect?\nA) All birds can fly. Penguins are birds. Penguins can fly.\nB) All fish swim.\nC) All apples are fruits.\nD) Some people are teachers.',
          options: [
            'All birds can fly. Penguins are birds. Penguins can fly.',
            'All fish swim.',
            'All apples are fruits.',
            'Some people are teachers.',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-3',
          question: 'Complete the sentence:\nAll roses are flowers. Some flowers fade. Therefore...',
          options: ['All roses fade', 'Some roses fade', 'Some flowers are roses', 'No roses fade'],
          correctIndex: 2,
        },
        {
          id: 'vl-4',
          question: 'Arrange the words in logical order:\nEgg, Chicken, Farm, Cook, Eat',
          options: [
            'Farm → Egg → Chicken → Cook → Eat',
            'Egg → Farm → Chicken → Eat → Cook',
            'Eat → Cook → Chicken → Egg → Farm',
            'Farm → Chicken → Egg → Cook → Eat',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-5',
          question: 'If all A are B, and all B are C, then...',
          options: ['All C are A', 'All A are C', 'All C are B', 'A and C are unrelated'],
          correctIndex: 1,
        },
        {
          id: 'vl-6',
          question: 'Find the correct sequence:\nInfant, Teenager, Adult, Child, Elder',
          options: [
            'Infant → Child → Teenager → Adult → Elder',
            'Child → Teenager → Infant → Adult → Elder',
            'Teenager → Adult → Elder → Infant → Child',
            'Infant → Teenager → Elder → Child → Adult',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-7',
          question: 'Which pair is not related?\nA) Writer – Pen\nB) Painter – Brush\nC) Chef – Oven\nD) Pilot – Pencil',
          options: ['Writer – Pen', 'Painter – Brush', 'Chef – Oven', 'Pilot – Pencil'],
          correctIndex: 3,
        },
        {
          id: 'vl-8',
          question: 'What follows logically?\nIf it rains, the ground gets wet. It’s raining. Therefore...',
          options: ['It’s sunny', 'The ground is wet', 'The ground is dry', 'We don’t know'],
          correctIndex: 1,
        },
        {
          id: 'vl-9',
          question: 'Which word is the opposite of the sequence?\nAlways, Often, Sometimes, Seldom, ?',
          options: ['Rarely', 'Never', 'Again', 'Regularly'],
          correctIndex: 1,
        },
        {
          id: 'vl-10',
          question: 'Which word is unrelated? Bread, Rice, Apple, Pasta',
          options: ['Bread', 'Rice', 'Apple', 'Pasta'],
          correctIndex: 2,
        },
        {
          id: 'vl-11',
          question: 'If 2 is company and 3 is a crowd, what is 1?',
          options: ['Alone', 'First', 'Leader', 'Odd'],
          correctIndex: 0,
        },
        {
          id: 'vl-12',
          question: 'Which comes next in the pattern?\nNorth, East, South, ?',
          options: ['West', 'Up', 'Down', 'Left'],
          correctIndex: 0,
        },
        {
          id: 'vl-13',
          question: 'Complete the sentence logically:\nSome mammals are not cats. All cats are animals. Therefore...',
          options: [
            'All mammals are animals',
            'Some animals are not mammals',
            'Some cats are mammals',
            'No mammals are cats',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-14',
          question: 'Which sentence is true?\nA) No rectangles are squares\nB) All squares are rectangles\nC) No shapes are triangles\nD) All circles are square',
          options: [
            'No rectangles are squares',
            'All squares are rectangles',
            'No shapes are triangles',
            'All circles are square',
          ],
          correctIndex: 1,
        },
        {
          id: 'vl-15',
          question: 'Choose the correct conclusion:\nAll fruits have seeds. Bananas have seeds. Therefore...',
          options: ['Bananas are not fruits', 'Bananas are fruits', 'Fruits are bananas', 'All fruits are bananas'],
          correctIndex: 1,
        },
        {
          id: 'vl-16',
          question: 'What is the correct sequence?\nDust, Sweep, Floor, Mop, Clean',
          options: [
            'Floor → Dust → Sweep → Mop → Clean',
            'Sweep → Dust → Mop → Clean → Floor',
            'Clean → Floor → Dust → Mop → Sweep',
            'Dust → Clean → Sweep → Floor → Mop',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-17',
          question: 'Which word doesn’t belong? Spoon, Fork, Knife, Brush',
          options: ['Spoon', 'Fork', 'Knife', 'Brush'],
          correctIndex: 3,
        },
        {
          id: 'vl-18',
          question: 'Logical opposite of "Always wins":',
          options: ['Never wins', 'Sometimes loses', 'Always loses', 'Occasionally wins'],
          correctIndex: 0,
        },
        {
          id: 'vl-19',
          question: 'If all poets are dreamers, and some dreamers are singers, then...',
          options: [
            'Some singers are poets',
            'All poets are singers',
            'Some poets are singers',
            'Some dreamers are poets',
          ],
          correctIndex: 3,
        },
        {
          id: 'vl-20',
          question: 'Choose the correct analogy:\nHour is to Minute as Day is to...',
          options: ['Year', 'Second', 'Week', 'Hour'],
          correctIndex: 2,
        },
        {
          id: 'vl-21',
          question: 'Which word is the opposite of “predictable”?',
          options: ['Boring', 'Exciting', 'Unexpected', 'Routine'],
          correctIndex: 2,
        },
        {
          id: 'vl-22',
          question: 'Which word completes the sequence?\nBeginner, Intermediate, ?',
          options: ['Novice', 'Master', 'Expert', 'Starter'],
          correctIndex: 1,
        },
        {
          id: 'vl-23',
          question: 'Choose the correct order:\nSeed, Tree, Fruit, Flower',
          options: [
            'Seed → Tree → Flower → Fruit',
            'Tree → Seed → Fruit → Flower',
            'Flower → Fruit → Tree → Seed',
            'Seed → Flower → Tree → Fruit',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-24',
          question: 'Find the illogical pair:\nA) Day – Night\nB) Hot – Cold\nC) Up – Down\nD) Tall – Soft',
          options: ['Day – Night', 'Hot – Cold', 'Up – Down', 'Tall – Soft'],
          correctIndex: 3,
        },
        {
          id: 'vl-25',
          question: 'If no cats are dogs and all dogs bark, then...',
          options: ['Some cats bark', 'No cats bark', 'All cats bark', 'All barking things are cats'],
          correctIndex: 1,
        },
        {
          id: 'vl-26',
          question: 'Choose the odd one out:\nRead, Write, Walk, Type',
          options: ['Read', 'Write', 'Walk', 'Type'],
          correctIndex: 2,
        },
        {
          id: 'vl-27',
          question: 'Which phrase is contradictory?\nA) Open secret\nB) Silent night\nC) Same difference\nD) Pretty ugly',
          options: ['Open secret', 'Silent night', 'Same difference', 'Pretty ugly'],
          correctIndex: 0,
        },
        {
          id: 'vl-28',
          question: 'Logical result:\nAll squares are rectangles. Some rectangles are blue. Therefore...',
          options: [
            'Some squares are blue',
            'All blue things are squares',
            'No squares are blue',
            'All rectangles are blue',
          ],
          correctIndex: 0,
        },
        {
          id: 'vl-29',
          question: 'Which pair is inconsistent?\nA) Teacher – Classroom\nB) Doctor – Hospital\nC) Chef – Restaurant\nD) Driver – Library',
          options: ['Teacher – Classroom', 'Doctor – Hospital', 'Chef – Restaurant', 'Driver – Library'],
          correctIndex: 3,
        },
        {
          id: 'vl-30',
          question: 'Choose the conclusion:\nAll stars shine. This object shines. Therefore...',
          options: ['It’s a star', 'It may be a star', 'All shining objects are stars', 'It is not a star'],
          correctIndex: 1,
        },
      ],
    abstractThinking: [
        {
          id: 'at-1',
          question: 'Which word doesn’t belong: Circle, Square, Triangle, Spiral',
          options: ['Circle', 'Square', 'Spiral', 'Triangle'],
          correctIndex: 2,
        },
        {
          id: 'at-2',
          question: 'What comes next: Sun is to day as moon is to...',
          options: ['Night', 'Star', 'Light', 'Planet'],
          correctIndex: 0,
        },
        {
          id: 'at-3',
          question: 'If all bloops are razzles, and all razzles are zorks, then all bloops are...',
          options: ['Zorks', 'Razzles', 'Bloops', 'None'],
          correctIndex: 0,
        },
        {
          id: 'at-4',
          question: 'Find the odd one out: Idea, Thought, Cloud, Plan',
          options: ['Cloud', 'Plan', 'Idea', 'Thought'],
          correctIndex: 0,
        },
        {
          id: 'at-5',
          question: 'Complete the analogy: Book is to Reading as Fork is to...',
          options: ['Writing', 'Drawing', 'Eating', 'Cooking'],
          correctIndex: 2,
        },
        {
          id: 'at-6',
          question: 'If a red object is heavier than a blue one, and the blue one is heavier than the green, which is the heaviest?',
          options: ['Red', 'Green', 'Blue', 'Cannot tell'],
          correctIndex: 0,
        },
        {
          id: 'at-7',
          question: 'Rearrange the letters of “ELNAC” to form a word. What is it?',
          options: ['CLEAN', 'CANAL', 'CLONE', 'LANCE'],
          correctIndex: 0,
        },
        {
          id: 'at-8',
          question: 'Find the pattern: AA, AB, AC, AD, ?',
          options: ['AE', 'BB', 'BA', 'AF'],
          correctIndex: 0,
        },
        {
          id: 'at-9',
          question: 'Which number doesn’t fit: 3, 5, 7, 11, 14, 17',
          options: ['5', '11', '14', '17'],
          correctIndex: 2,
        },
        {
          id: 'at-10',
          question: 'Which concept is the most abstract? Table, Happiness, Chair, Door',
          options: ['Table', 'Happiness', 'Chair', 'Door'],
          correctIndex: 1,
        },
        {
          id: 'at-11',
          question: 'If cats are animals and all animals breathe, what do cats do?',
          options: ['Sleep', 'Run', 'Breathe', 'Fly'],
          correctIndex: 2,
        },
        {
          id: 'at-12',
          question: 'Which of these is a metaphor? A) She is like the wind  B) She moves as fast as a horse  C) She is a storm  D) She runs every day',
          options: ['She is like the wind', 'She moves as fast as a horse', 'She is a storm', 'She runs every day'],
          correctIndex: 2,
        },
        {
          id: 'at-13',
          question: 'You see a boat filled with people. It hasn’t sunk, but when you look again, you don’t see a single person. Why?',
          options: ['They all left', 'They were below deck', 'They were all married', 'It was a trick'],
          correctIndex: 2,
        },
        {
          id: 'at-14',
          question: 'What word is always pronounced wrong?',
          options: ['Wrong', 'Right', 'Wring', 'None'],
          correctIndex: 0,
        },
        {
          id: 'at-15',
          question: 'What gets wetter the more it dries?',
          options: ['Sponge', 'Water', 'Towel', 'Air'],
          correctIndex: 2,
        },
        {
          id: 'at-16',
          question: 'Which pair is unrelated? Painter–Brush, Writer–Pen, Chef–Knife, Singer–Hammer',
          options: ['Painter–Brush', 'Writer–Pen', 'Chef–Knife', 'Singer–Hammer'],
          correctIndex: 3,
        },
        {
          id: 'at-17',
          question: 'Which option is not a form of communication? Speech, Letter, Silence, Text',
          options: ['Speech', 'Letter', 'Silence', 'Text'],
          correctIndex: 2,
        },
        {
          id: 'at-18',
          question: 'What has keys but can’t open locks? Map, Clock, Piano, Wallet',
          options: ['Map', 'Clock', 'Piano', 'Wallet'],
          correctIndex: 2,
        },
        {
          id: 'at-19',
          question: 'Which word is most unlike the others? Trust, Lie, Believe, Honesty',
          options: ['Trust', 'Lie', 'Believe', 'Honesty'],
          correctIndex: 1,
        },
        {
          id: 'at-20',
          question: 'Which shape has no edges? Square, Triangle, Circle, Cube',
          options: ['Square', 'Triangle', 'Circle', 'Cube'],
          correctIndex: 2,
        },
        {
          id: 'at-21',
          question: 'If I am thinking of a number, double it, subtract 6, and the result is 10 — what was the number?',
          options: ['6', '7', '8', '9'],
          correctIndex: 2,
        },
        {
          id: 'at-22',
          question: 'If all birds can fly and penguins are birds, what’s wrong?',
          options: ['All true', 'Penguins can’t fly', 'Birds can’t fly', 'No birds exist'],
          correctIndex: 1,
        },
        {
          id: 'at-23',
          question: 'Find the missing word: You can’t spell “_” without “I”',
          options: ['Idea', 'Success', 'Win', 'Team'],
          correctIndex: 3,
        },
        {
          id: 'at-24',
          question: 'If blue is red, and red is green, what color is the sky?',
          options: ['Blue', 'Green', 'Red', 'Trick question'],
          correctIndex: 3,
        },
        {
          id: 'at-25',
          question: 'Which one is a paradox? I always lie, The sky is blue, Cats meow, Fire is hot',
          options: ['I always lie', 'The sky is blue', 'Cats meow', 'Fire is hot'],
          correctIndex: 0,
        },
        {
          id: 'at-26',
          question: 'What has no beginning, no end, and no middle?',
          options: ['Ocean', 'Earth', 'Circle', 'Space'],
          correctIndex: 2,
        },
        {
          id: 'at-27',
          question: 'Find the logical pair: Fire is to hot as ice is to...',
          options: ['Wet', 'Cold', 'Snow', 'Dry'],
          correctIndex: 1,
        },
        {
          id: 'at-28',
          question: 'If all squares are rectangles, but not all rectangles are squares, then which is true?',
          options: ['Squares are not rectangles', 'All rectangles are squares', 'Squares are rectangles', 'None are related'],
          correctIndex: 2,
        },
        {
          id: 'at-29',
          question: 'Which best completes the pattern: Dog, Cat, Mouse, Cheese, ?',
          options: ['Trap', 'Rat', 'House', 'Hole'],
          correctIndex: 3,
        },
        {
          id: 'at-30',
          question: 'If you’re in a race and pass the person in second place, what place are you in?',
          options: ['First', 'Second', 'Third', 'Last'],
          correctIndex: 1,
        },
        {
          id: 'at-31',
          question: 'A father and son are in a car crash. The father dies instantly. The boy is rushed to surgery. The surgeon says, “I can’t operate on this boy — he’s my son.” Who is the surgeon?',
          options: ['Stepfather', 'Brother', 'Mother', 'Uncle'],
          correctIndex: 2,
        },
        {
          id: 'at-32',
          question: 'Which statement is true if the following are all false? 1) All elephants can dance. 2) No animals can dance. 3) Some animals can dance.',
          options: ['1', '2', '3', 'None'],
          correctIndex: 2,
        },
        {
          id: 'at-33',
          question: 'You see a clock that’s stopped at 3:00. It’s correct twice a day. What other time is it also correct?',
          options: ['3:00 AM', '12:00 PM', '6:00 AM', '9:00 PM'],
          correctIndex: 0,
        },
        {
          id: 'at-34',
          question: 'If some truths are lies and all lies are not facts, what can you conclude?',
          options: ['Some truths are facts', 'Some lies are truths', 'All facts are lies', 'Nothing is true'],
          correctIndex: 1,
        },
        {
          id: 'at-35',
          question: 'You meet a person on an island. They say: “Everyone here always lies. I\'m lying right now.” What can you conclude?',
          options: ['They are lying', 'They are telling the truth', 'The statement is meaningless', 'All islanders lie'],
          correctIndex: 0,
        },
        {
          id: 'at-36',
          question: 'What comes next: 1 = 5, 2 = 15, 3 = 215, 4 = 3215, 5 = ?',
          options: ['43215', '4321', '54321', '0'],
          correctIndex: 0,
        },
        {
          id: 'at-37',
          question: 'You are in a room with 3 switches and a closed door. One switch turns on a light in the next room. You may flip switches and open the door only once. How do you find the right switch?',
          options: ['Use trial and error', 'Flip one, wait, turn it off, flip another', 'Flip all and open door', 'You can’t know'],
          correctIndex: 1,
        },
        {
          id: 'at-38',
          question: 'Which is heavier: A kilogram of steel or a kilogram of feathers?',
          options: ['Steel', 'Feathers', 'Equal', 'Depends'],
          correctIndex: 2,
        },
        {
          id: 'at-39',
          question: 'If time is money and you waste time, what are you losing?',
          options: ['Energy', 'Money', 'Opportunity', 'Memory'],
          correctIndex: 1,
        },
        {
          id: 'at-40',
          question: 'You’re told to pick one box out of three:\nOne says "The prize is not in this box."\nOne says "The prize is in this box."\nOne says "This box lies."\nIf only one statement is true — where is the prize?',
          options: ['Box 1', 'Box 2', 'Box 3', 'Not enough data'],
          correctIndex: 0,
        },
      ],
    arithmeticSpeed: [
      {
        id: 'as-1',
        question: 'What is 87 × 6?',
        options: ['492', '522', '508', '544'],
        correctIndex: 2,
      },
      {
        id: 'as-2',
        question: 'What is (125 ÷ 5) + (18 × 2)?',
        options: ['71', '66', '64', '69'],
        correctIndex: 1,
      },
      {
        id: 'as-3',
        question: 'What is 20% of 345?',
        options: ['68', '69', '70', '72'],
        correctIndex: 2,
      },
      {
        id: 'as-4',
        question: 'What is 3/4 of 128?',
        options: ['94', '96', '98', '100'],
        correctIndex: 1,
      },
      {
        id: 'as-5',
        question: 'What is (45 + 60) × 3 – 50?',
        options: ['265', '275', '295', '305'],
        correctIndex: 2,
      },
      {
        id: 'as-6',
        question: 'What is 18² – 17²?',
        options: ['33', '35', '37', '39'],
        correctIndex: 0,
      },
      {
        id: 'as-7',
        question: 'What is 12.5% of 480?',
        options: ['58', '60', '62', '64'],
        correctIndex: 1,
      },
      {
        id: 'as-8',
        question: 'What is 144 ÷ (6 × 2)?',
        options: ['12', '10', '14', '16'],
        correctIndex: 1,
      },
      {
        id: 'as-9',
        question: 'What is 5³ + 2² × 3?',
        options: ['131', '137', '139', '143'],
        correctIndex: 1,
      },
      {
        id: 'as-10',
        question: 'What is the result of 100 – 40 ÷ 4 + 6 × 3?',
        options: ['114', '118', '120', '124'],
        correctIndex: 0,
      },
      {
        id: 'as-11',
        question: 'What is 11 × 11 + 12 × 12?',
        options: ['265', '265', '275', '285'],
        correctIndex: 0,
      },
      {
        id: 'as-12',
        question: 'What is 35% of 220?',
        options: ['76', '77', '78', '79'],
        correctIndex: 2,
      },
      {
        id: 'as-13',
        question: 'What is (64 ÷ 4) + (9 × 2) – 7?',
        options: ['29', '30', '31', '33'],
        correctIndex: 0,
      },
      {
        id: 'as-14',
        question: 'What is (150 – 25) × 2 + 50?',
        options: ['250', '275', '285', '300'],
        correctIndex: 1,
      },
      {
        id: 'as-15',
        question: 'What is the value of 2.5 × 16 + 1.5 × 12?',
        options: ['68', '70', '72', '74'],
        correctIndex: 0,
      },
      {
        id: 'as-16',
        question: 'What is the sum of the first five odd numbers?',
        options: ['25', '30', '35', '40'],
        correctIndex: 0,
      },
      {
        id: 'as-17',
        question: 'What is 90 ÷ (6 + 3) × 2?',
        options: ['18', '20', '22', '24'],
        correctIndex: 2,
      },
      {
        id: 'as-18',
        question: 'What is 0.75 × 160?',
        options: ['110', '115', '120', '125'],
        correctIndex: 2,
      },
      {
        id: 'as-19',
        question: 'What is 20² + 15² – 25²?',
        options: ['100', '90', '80', '70'],
        correctIndex: 0,
      },
      {
        id: 'as-20',
        question: 'What is (250 ÷ 5) + (360 ÷ 6)?',
        options: ['103', '105', '107', '110'],
        correctIndex: 0,
      },
      {
        id: 'as-21',
        question: 'What is (2³ × 3²) + 5?',
        options: ['73', '77', '81', '85'],
        correctIndex: 1,
      },
      {
        id: 'as-22',
        question: 'What is (45 × 2) – (9 × 5)?',
        options: ['45', '50', '55', '60'],
        correctIndex: 2,
      },
      {
        id: 'as-23',
        question: 'What is 75% of 320?',
        options: ['230', '235', '240', '245'],
        correctIndex: 2,
      },
      {
        id: 'as-24',
        question: 'What is (0.5 × 48) + (0.25 × 64)?',
        options: ['40', '42', '44', '46'],
        correctIndex: 0,
      },
      {
        id: 'as-25',
        question: 'What is the average of: 18, 22, 30, 40?',
        options: ['27', '28', '27.5', '29'],
        correctIndex: 2,
      },
      {
        id: 'as-26',
        question: 'What is the result of 13² – 11²?',
        options: ['36', '40', '44', '48'],
        correctIndex: 0,
      },
      {
        id: 'as-27',
        question: 'What is 4.5 × (8 + 6)?',
        options: ['60', '63', '66', '69'],
        correctIndex: 1,
      },
      {
        id: 'as-28',
        question: 'What is (3 × 17) – (2 × 9)?',
        options: ['33', '35', '37', '39'],
        correctIndex: 0,
      },
      {
        id: 'as-29',
        question: 'What is 2.25 × 16?',
        options: ['36', '38', '36.5', '36'],
        correctIndex: 0,
      },
      {
        id: 'as-30',
        question: 'What is (10 + 20 + 30) × 1.5?',
        options: ['90', '95', '100', '90'],
        correctIndex: 2,
      },
    ],
  
    numberSequences: [
      {
        id: 'ns-1',
        question: 'What comes next: 3, 6, 12, 24, ?',
        options: ['36', '48', '60', '72'],
        correctIndex: 1,
      },
      {
        id: 'ns-2',
        question: 'What comes next: 101, 99, 96, 92, ?',
        options: ['88', '89', '90', '91'],
        correctIndex: 0,
      },
      {
        id: 'ns-3',
        question: 'What comes next: 2, 5, 10, 17, 26, ?',
        options: ['35', '36', '37', '38'],
        correctIndex: 1,
      },
      {
        id: 'ns-4',
        question: 'What comes next: 1, 4, 9, 16, 25, ?',
        options: ['35', '36', '37', '38'],
        correctIndex: 1,
      },
      {
        id: 'ns-5',
        question: 'What comes next: 144, 72, 36, 18, ?',
        options: ['10', '8', '9', '6'],
        correctIndex: 2,
      },
      {
        id: 'ns-6',
        question: 'What comes next: 1, 3, 7, 15, 31, ?',
        options: ['63', '61', '59', '65'],
        correctIndex: 0,
      },
      {
        id: 'ns-7',
        question: 'What comes next: 5, 10, 20, 40, ?',
        options: ['45', '60', '70', '80'],
        correctIndex: 3,
      },
      {
        id: 'ns-8',
        question: 'What comes next: 90, 81, 72, 63, ?',
        options: ['54', '55', '57', '59'],
        correctIndex: 0,
      },
      {
        id: 'ns-9',
        question: 'What comes next: 3, 5, 9, 17, 33, ?',
        options: ['47', '61', '59', '63'],
        correctIndex: 1,
      },
      {
        id: 'ns-10',
        question: 'What comes next: 8, 24, 12, 36, 18, ?',
        options: ['54', '48', '60', '30'],
        correctIndex: 0,
      },
      {
        id: 'ns-11',
        question: 'What comes next: 121, 100, 81, 64, ?',
        options: ['49', '36', '30', '40'],
        correctIndex: 0,
      },
      {
        id: 'ns-12',
        question: 'What comes next: 1, 2, 4, 7, 11, ?',
        options: ['15', '16', '17', '18'],
        correctIndex: 0,
      },
      {
        id: 'ns-13',
        question: 'What comes next: 2, 6, 18, 54, ?',
        options: ['108', '162', '216', '120'],
        correctIndex: 1,
      },
      {
        id: 'ns-14',
        question: 'What comes next: 10, 7, 4, 1, ?',
        options: ['0', '-1', '-2', '1'],
        correctIndex: 1,
      },
      {
        id: 'ns-15',
        question: 'What comes next: 1, 3, 6, 10, 15, ?',
        options: ['21', '20', '22', '24'],
        correctIndex: 0,
      },
      {
        id: 'ns-16',
        question: 'What comes next: 81, 27, 9, 3, ?',
        options: ['0', '1', '2', '4'],
        correctIndex: 1,
      },
      {
        id: 'ns-17',
        question: 'What comes next: 100, 50, 25, ?',
        options: ['10', '12.5', '15', '20'],
        correctIndex: 1,
      },
      {
        id: 'ns-18',
        question: 'What comes next: 0, 1, 1, 2, 3, 5, ?',
        options: ['7', '8', '9', '10'],
        correctIndex: 1,
      },
      {
        id: 'ns-19',
        question: 'What comes next: 2, 3, 5, 7, 11, ?',
        options: ['12', '13', '15', '17'],
        correctIndex: 1,
      },
      {
        id: 'ns-20',
        question: 'What comes next: 40, 36, 32, 28, ?',
        options: ['26', '24', '22', '20'],
        correctIndex: 1,
      },
      {
        id: 'ns-21',
        question: 'What comes next: 2, 4, 3, 6, 5, 10, ?',
        options: ['7', '8', '9', '12'],
        correctIndex: 0,
      },
      {
        id: 'ns-22',
        question: 'What comes next: 1, 10, 100, ?',
        options: ['1000', '110', '120', '150'],
        correctIndex: 0,
      },
      {
        id: 'ns-23',
        question: 'What comes next: 20, 17, 13, 8, ?',
        options: ['2', '4', '5', '6'],
        correctIndex: 1,
      },
      {
        id: 'ns-24',
        question: 'What comes next: 2, 5, 10, 17, ?',
        options: ['24', '26', '28', '30'],
        correctIndex: 1,
      },
      {
        id: 'ns-25',
        question: 'What comes next: 0.5, 1, 2, 4, ?',
        options: ['6', '7', '8', '9'],
        correctIndex: 2,
      },
      {
        id: 'ns-26',
        question: 'What comes next: 99, 88, 77, ?',
        options: ['66', '67', '68', '70'],
        correctIndex: 0,
      },
      {
        id: 'ns-27',
        question: 'What comes next: 3, 6, 11, 18, ?',
        options: ['25', '26', '27', '28'],
        correctIndex: 1,
      },
      {
        id: 'ns-28',
        question: 'What comes next: 50, 100, 200, 400, ?',
        options: ['600', '700', '800', '900'],
        correctIndex: 2,
      },
      {
        id: 'ns-29',
        question: 'What comes next: 17, 34, 68, ?',
        options: ['85', '102', '119', '136'],
        correctIndex: 3,
      },
      {
        id: 'ns-30',
        question: 'What comes next: 6, 11, 21, 36, ?',
        options: ['46', '54', '61', '65'],
        correctIndex: 1,
      },
    ],
  
    logicWordProblems: [
      {
        id: 'lw-1',
        question: 'A bakery sells 8 muffins per box. If you buy 7 boxes, how many muffins do you have?',
        options: ['54', '56', '58', '60'],
        correctIndex: 1,
      },
      {
        id: 'lw-2',
        question: 'John is twice as old as Peter. If Peter is 14, how old is John?',
        options: ['26', '27', '28', '30'],
        correctIndex: 2,
      },
      {
        id: 'lw-3',
        question: 'A car travels 90 km in 1.5 hours. What is its speed in km/h?',
        options: ['55', '60', '65', '70'],
        correctIndex: 1,
      },
      {
        id: 'lw-4',
        question: 'A train departs at 14:35 and arrives at 17:20. How long is the journey?',
        options: ['2 h 35 min', '2 h 45 min', '3 h', '2 h 50 min'],
        correctIndex: 0,
      },
      {
        id: 'lw-5',
        question: 'You buy 3 pens at $2.50 each and a notebook for $6. What’s the total cost?',
        options: ['$13.50', '$14.00', '$14.50', '$15.00'],
        correctIndex: 0,
      },
      {
        id: 'lw-6',
        question: 'A farmer has 4 cows. Each cow gives 8 liters of milk per day. How much milk in 5 days?',
        options: ['120 l', '140 l', '160 l', '180 l'],
        correctIndex: 1,
      },
      {
        id: 'lw-7',
        question: 'If a pizza is cut into 8 slices and you eat 3, what fraction is left?',
        options: ['5/8', '3/8', '1/2', '2/3'],
        correctIndex: 0,
      },
      {
        id: 'lw-8',
        question: 'Lisa read 90 pages in 3 hours. How many pages per hour?',
        options: ['25', '30', '35', '40'],
        correctIndex: 1,
      },
      {
        id: 'lw-9',
        question: 'A toy costs $18 after a 10% discount. What was the original price?',
        options: ['$20', '$22', '$24', '$25'],
        correctIndex: 0,
      },
      {
        id: 'lw-10',
        question: 'A tank holds 120 liters. You use 15 liters per day. How many full days will it last?',
        options: ['7', '8', '9', '10'],
        correctIndex: 1,
      },
      {
        id: 'lw-11',
        question: 'A movie starts at 16:45 and runs for 2 hours 20 minutes. When does it end?',
        options: ['18:55', '19:05', '19:10', '19:15'],
        correctIndex: 1,
      },
      {
        id: 'lw-12',
        question: 'A rope is 3.6 meters long. If it is cut into 6 equal parts, how long is each part?',
        options: ['0.5 m', '0.6 m', '0.7 m', '0.8 m'],
        correctIndex: 1,
      },
      {
        id: 'lw-13',
        question: 'A recipe needs 3/4 cup of sugar. If you triple the recipe, how much sugar do you need?',
        options: ['2 cups', '2 1/4 cups', '2 1/2 cups', '2 3/4 cups'],
        correctIndex: 1,
      },
      {
        id: 'lw-14',
        question: 'A pen costs $2. A ruler costs $3 more. What is the cost of both?',
        options: ['$5', '$6', '$7', '$8'],
        correctIndex: 2,
      },
      {
        id: 'lw-15',
        question: 'If a taxi charges $5 base fare + $2/km, how much is a 6 km trip?',
        options: ['$15', '$16', '$17', '$18'],
        correctIndex: 2,
      },
      {
        id: 'lw-16',
        question: 'Anna buys 4 books for $7 each. She pays with a $50 bill. How much change?',
        options: ['$20', '$21', '$22', '$23'],
        correctIndex: 2,
      },
      {
        id: 'lw-17',
        question: 'You earn $12/hour and work 6.5 hours. How much do you earn?',
        options: ['$78', '$79', '$80', '$78'],
        correctIndex: 0,
      },
      {
        id: 'lw-18',
        question: 'A pack has 24 batteries. You use 3 per week. How many weeks will it last?',
        options: ['7', '8', '9', '10'],
        correctIndex: 1,
      },
      {
        id: 'lw-19',
        question: 'Mike runs 400 meters in 80 seconds. What is his speed (m/s)?',
        options: ['4', '5', '6', '7'],
        correctIndex: 1,
      },
      {
        id: 'lw-20',
        question: 'You have 3 blue, 2 red, and 5 green marbles. What’s the total?',
        options: ['9', '10', '11', '12'],
        correctIndex: 1,
      },
      {
        id: 'lw-21',
        question: 'A square has side 12 cm. What is its area?',
        options: ['144', '120', '130', '135'],
        correctIndex: 0,
      },
      {
        id: 'lw-22',
        question: 'A book has 480 pages. You read 40 pages/day. In how many days will you finish it?',
        options: ['10', '11', '12', '13'],
        correctIndex: 2,
      },
      {
        id: 'lw-23',
        question: 'If 5 people share $200 equally, how much does each get?',
        options: ['$40', '$50', '$60', '$70'],
        correctIndex: 0,
      },
      {
        id: 'lw-24',
        question: 'A store increases prices by 20%. An item was $150. What’s the new price?',
        options: ['$170', '$175', '$180', '$185'],
        correctIndex: 2,
      },
      {
        id: 'lw-25',
        question: 'A train covers 300 km in 4 hours. What’s the average speed?',
        options: ['70 km/h', '75 km/h', '80 km/h', '85 km/h'],
        correctIndex: 2,
      },
      {
        id: 'lw-26',
        question: 'Jane saves $15/week. How much after 9 weeks?',
        options: ['$130', '$135', '$140', '$145'],
        correctIndex: 1,
      },
      {
        id: 'lw-27',
        question: 'A triangle has base 10 cm and height 8 cm. What is its area?',
        options: ['40', '50', '60', '80'],
        correctIndex: 0,
      },
      {
        id: 'lw-28',
        question: 'A gallon of paint covers 350 sq ft. How many gallons for 1,400 sq ft?',
        options: ['3', '4', '5', '6'],
        correctIndex: 1,
      },
      {
        id: 'lw-29',
        question: 'You score 80, 75, and 85 on tests. What’s the average?',
        options: ['80', '82', '83', '84'],
        correctIndex: 0,
      },
      {
        id: 'lw-30',
        question: 'A pizza has 12 slices. You eat 1/3 of it. How many slices is that?',
        options: ['3', '4', '5', '6'],
        correctIndex: 1,
      },
    ],
  
    fractionsPercentages: [
      {
        id: 'fp-1',
        question: 'What is 3/4 of 64?',
        options: ['46', '48', '50', '52'],
        correctIndex: 1,
      },
      {
        id: 'fp-2',
        question: 'What is 25% of 360?',
        options: ['85', '90', '95', '100'],
        correctIndex: 1,
      },
      {
        id: 'fp-3',
        question: 'Which is greater: 2/3 or 3/5?',
        options: ['2/3', '3/5', 'Equal', 'Cannot say'],
        correctIndex: 0,
      },
      {
        id: 'fp-4',
        question: 'What is 7/8 as a percentage?',
        options: ['85%', '87.5%', '88%', '90%'],
        correctIndex: 1,
      },
      {
        id: 'fp-5',
        question: 'What is 0.25 as a fraction?',
        options: ['1/2', '1/3', '1/4', '2/5'],
        correctIndex: 2,
      },
      {
        id: 'fp-6',
        question: 'What is 60% of 250?',
        options: ['145', '150', '155', '160'],
        correctIndex: 1,
      },
      {
        id: 'fp-7',
        question: 'A price is increased by 20%. If the original price is $150, what is the new price?',
        options: ['$170', '$175', '$180', '$185'],
        correctIndex: 2,
      },
      {
        id: 'fp-8',
        question: 'Reduce the fraction 45/60.',
        options: ['3/4', '2/3', '4/5', '5/6'],
        correctIndex: 0,
      },
      {
        id: 'fp-9',
        question: 'What is 2 ½ + 3 ¼?',
        options: ['5 ½', '5 ¾', '6', '6 ¼'],
        correctIndex: 1,
      },
      {
        id: 'fp-10',
        question: 'What is 15% of 80?',
        options: ['10', '11', '12', '14'],
        correctIndex: 2,
      },
      {
        id: 'fp-11',
        question: 'Convert 5/8 to a percentage.',
        options: ['62.5%', '60%', '65%', '68%'],
        correctIndex: 0,
      },
      {
        id: 'fp-12',
        question: 'What is 40% of 90?',
        options: ['34', '35', '36', '38'],
        correctIndex: 2,
      },
      {
        id: 'fp-13',
        question: 'If a number is reduced by 25%, and becomes 75, what was the original number?',
        options: ['95', '96', '100', '105'],
        correctIndex: 2,
      },
      {
        id: 'fp-14',
        question: 'What is 1/5 of 225?',
        options: ['40', '45', '50', '55'],
        correctIndex: 1,
      },
      {
        id: 'fp-15',
        question: 'What is 10% of 250, then doubled?',
        options: ['40', '45', '50', '60'],
        correctIndex: 2,
      },
      {
        id: 'fp-16',
        question: 'What is 2/3 – 1/4?',
        options: ['4/9', '5/12', '3/8', '7/16'],
        correctIndex: 1,
      },
      {
        id: 'fp-17',
        question: 'Increase 120 by 30%.',
        options: ['150', '156', '160', '165'],
        correctIndex: 0,
      },
      {
        id: 'fp-18',
        question: 'Decrease 200 by 15%.',
        options: ['165', '170', '175', '180'],
        correctIndex: 2,
      },
      {
        id: 'fp-19',
        question: 'What is 120% of 80?',
        options: ['90', '96', '100', '105'],
        correctIndex: 1,
      },
      {
        id: 'fp-20',
        question: 'What is 5/6 of 72?',
        options: ['58', '59', '60', '61'],
        correctIndex: 2,
      },
      {
        id: 'fp-21',
        question: 'What is the value of 3/8 + 5/8?',
        options: ['1', '7/8', '9/8', '5/6'],
        correctIndex: 0,
      },
      {
        id: 'fp-22',
        question: 'What is 1/2 of 3/4?',
        options: ['3/8', '1/4', '2/3', '3/4'],
        correctIndex: 0,
      },
      {
        id: 'fp-23',
        question: 'What percent of 80 is 12?',
        options: ['12%', '14%', '15%', '18%'],
        correctIndex: 2,
      },
      {
        id: 'fp-24',
        question: 'What is ⅝ as a decimal?',
        options: ['0.5', '0.625', '0.675', '0.7'],
        correctIndex: 1,
      },
      {
        id: 'fp-25',
        question: 'What is ⅗ × 45?',
        options: ['26', '27', '28', '27'],
        correctIndex: 1,
      },
      {
        id: 'fp-26',
        question: 'What is 120 reduced by ⅓?',
        options: ['70', '75', '80', '85'],
        correctIndex: 2,
      },
      {
        id: 'fp-27',
        question: 'What is ¾ of 2/3?',
        options: ['½', '3/4', '5/6', '1'],
        correctIndex: 0,
      },
      {
        id: 'fp-28',
        question: 'A price of $200 is decreased by 40%. What is the new price?',
        options: ['$120', '$130', '$140', '$150'],
        correctIndex: 0,
      },
      {
        id: 'fp-29',
        question: 'A class has 30 students. ⅖ are boys. How many boys?',
        options: ['11', '12', '13', '14'],
        correctIndex: 1,
      },
      {
        id: 'fp-30',
        question: 'What is 90 increased by ⅕?',
        options: ['104', '106', '108', '110'],
        correctIndex: 2,
      },
    ],
  }
  
  export default QUESTIONS
  